const Constants = {
  actions: {
    SENDMESSAGE: 'SENDMESSAGE',
    SETNAME: 'SETNAME',
    MESSAGERECEIVED: 'MESSAGERECEIVED',
    FETCHNAME: 'FECHNAME',
    HASMESSAGES: 'HASMESSAGES',
    FETCHPROPERTIES: 'FETCHPROPERTIES',
    SIGNOUT: 'SIGNOUT',
  },

  events: {
    ERROR: 'ERROR',
    CHANGE: 'CHANGE',
    SAVE: 'SAVE',
    MESSAGERECEIVED: 'MESSAGERECEIVED',
    FETCHNAME: 'FECHNAME',
    MESSAGE: 'MESSAGE',
    CHATISEMPTY: 'CHATISEMPTY',
    PROPERTYCHANGE: 'PROPERTYCHANGE',
  },
};

module.exports = Constants;
